replicas: 1
minimumMasterNodes: 1
persistence:
  enabled: false

clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

